services:
  - type: web
    name: telegram-deploy-bot
    env: python
    pythonVersion: 3.12.17
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN